apiVersion: v1
kind: Pod
metadata:
  name: nginx-fieldref
  labels:
    app: dac
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: tmp-vol
  volumes:
    - name: tmp-vol
      hostPath:
        path: /tmp
        type: Directory
  
  initContainers:
    - name: init-config
      image: busybox
      volumeMounts:
        - mountPath: /tmp
          name: tmp-vol
      command: [ "sh", "-c", "echo $MY_POD_IP > /tmp/index.html" ]

      env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
  restartPolicy: Never

